version: 1.0
provider:
  name: openfaas
  gateway: https://gateway.fn.rnd.dev

#   name: faas
#   gateway: http://127.0.0.1:8080
  
functions:
  gohash:
    lang: go
    handler: ./gohash
    image: randomnerd/gohash:latest
